[package]
name = "ckmeans"
description = "A Rust implementation of Wang and Song's Ckmeans clustering algorithm"
version = "1.0.6"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/urschrei/ckmeans"
documentation = "https://docs.rs/ckmeans"
readme = "README.md"
keywords = ["gis", "geo", "spatial", "clustering"]
autobenches = true
rust-version = "1.70"
categories = ["science::geo"]

[badges]
maintenance = { status = "passively-maintained" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
headers = ["cbindgen"]

[dependencies]
js-sys = "0.3.64"
libc = "0.2.147"
num-traits = "0.2.16"
wasm-bindgen = "0.2"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
rand_distr = "0.4.3"

[build-dependencies]
cbindgen = { version = "0.24.5", default-features=false, optional = true }

[[bench]]
name = "benchmark"
harness = false

[lib]
name = "ckmeans"
crate-type = ["rlib", "cdylib"]
test = true
doctest = true
doc = true
